name: Build Workflow
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev
      - main
env:
  ENVIROMENT: dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare env for CI
        working-directory: ./Server
        run: cp .env.sample .env
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.3.1
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: Server/go.mod
          cache-dependency-path: Server/go.sum
      - name: Install Client Dependencies
        working-directory: ./Client
        run: bun install
      - name: Install Server Dependencies
        working-directory: ./Server
        run: go mod tidy
      - name: Building Client Side
        working-directory: ./Client
        run: bun run build
      - name: Building Server Side
        working-directory: ./Server
        run: go run cli/main.go build
      - name: Building MailServer Side
        working-directory: ./MailServer
        run: bun run build
